products_service_a:
  build: .
  ports:
    - "80:8000"

products_service_b:
  build: .
  ports:
    - "80:8000"

products_service_c:
  build: .
  ports:
    - "80:8000"

haproxy:
  image: hypriot/rpi-haproxy
  volumes:
   - haproxy:/haproxy-override
  links:
   - products_service_a
   - products_service_b
   - products_service_c
  ports:
   - "80:80"
   - "70:70"

  expose:
   - "80"
   - "70"
