producta:
  build: .
  expose:
    - 80
  environment:
    - PORT=80

productb:
  build: .
  expose:
    - 80
  environment:
    - PORT=80

productc:
  build: .
  expose:
    - 80
  environment:
    - PORT=80

haproxy:
  image: hypriot/rpi-haproxy
  volumes:
   - ./haproxy:/haproxy-override
  links:
   - producta
   - productb
   - productc
  ports:
   - "80:80"
   - "70:70"

  expose:
   - "80"
   - "70"
